#!/bin/bash

####################################################### 加载配置文件 ########################################################
# 使用$(eval echo ~$SUDO_USER)获取用户家目录，避免sudo执行时获取到root的家目录
PROFILE_FILE=$(eval echo ~$SUDO_USER)/.jm_profile
ERROR_LOG=./error.log
echo "" >$ERROR_LOG
if [[ -e $PROFILE_FILE ]]; then
    source $PROFILE_FILE
fi
########################################################################################################################

function getPid() {
    jar_name=$1
    PID=$(ps aux | grep "${jar_name}" | grep -v 'grep' | grep -v 'sudo' | grep -v 'nohup' | tr -s ' ' | cut -d ' ' -f 2)
    echo "$PID"
}

function show_log(){
    if [[ "$1" == "-e" ]]; then
        if [ ! -f "${APP_LOGS_ERROR_FILE}" ]; then
            log_error "错误日志文件[${APP_LOGS_ERROR_FILE}]不存在，请正确配置"
            exit 1
        fi
        
        tail -f -n 500 "${APP_LOGS_ERROR_FILE}"
    else
    if [ ! -f "${APP_LOGS_INFO_FILE}" ]; then
            log_error "日志文件[${APP_LOGS_INFO_FILE}]不存在，请正确配置"
            exit 1
        fi
        tail -f -n 500 "${APP_LOGS_INFO_FILE}"
    fi
}


# 重启进程
function restart() {
    jar_name="$JAR_NAME"
    if [[ -z "$jar_name" ]]; then
        log_info 'The JAR_NAME have not been configured, please use [jm cfg] command to configure the jar name'
        exit 1
    fi
    PID=$(getPid "$jar_name")
    if [ -n "$PID" ]; then
        kill -9 "$PID" >/dev/null 2>$ERROR_LOG
        fn_log "Kill old $jar_name (PID: $PID)..."
    fi

    log_info "Start $jar_name..."

    #将字符串解析为多个参数的变量
    # read -r -a jvm_options <<< "$JVM_OPTIONS"
    nohup java $JVM_OPTIONS -jar "$APP_PATH/$jar_name" >/dev/null 2>$ERROR_LOG &
    checkStatus "$jar_name"
}

# 停止进程
function stop() {
    jar_name="$JAR_NAME"
    if [[ -z "$jar_name" ]]; then
        log_info 'The JAR_NAME have not been configured, please use [jm cfg] command to configure the jar name'
        exit 1
    fi
    PID=$(getPid "$jar_name")
    if [ -n "$PID" ]; then
        kill -9 "$PID" >/dev/null 2>$ERROR_LOG
        fn_log "Kill old $jar_name (PID: $PID)..."
    fi
    log_info "$jar_name (PID: $PID) stoped."
}

# 停止进程
function remote_stop() {
    for host in $DEPLOY_HOSTS; do
        log_info "执行停止命令[$host]..."
        ssh "admin@$host" 'jm stp'
        log_info "停止命令执行完成[$host]...\n"
  done
}

function remote_restart() {
  for host in $DEPLOY_HOSTS; do
        log_info "执行启动命令[$host]..."
        ssh "admin@$host" 'jm rst'
        log_info "启动命令执行完成[$host]...\n"
  done
}

function deploy(){
    jar_name="$JAR_NAME"
    host="$DEPLOY_HOSTS"
    source_path="$APP_SOURCE_PATH"
     if [[ -z "$jar_name" ]]; then
        log_info 'The JAR_NAME have not been configured, please use [jm cfg] command to configure the jar name'
        exit 1
    fi
     if [[ -z "$host" ]]; then
        log_info 'The DEPLOY_HOSTS have not been configured, please use [jm cfg] command to configure the jar name'
        exit 1
    fi
     if [[ -z "$source_path" ]]; then
        log_info 'The APP_SOURCE_PATH have not been configured, please use [jm cfg] command to configure the jar name'
        exit 1
    fi
    for host in $DEPLOY_HOSTS; do
        fn_log "开始上传部署文件[$host]..."
        scp "$source_path/$jar_name" admin@$host:"$APP_PATH/$jar_name"
        fn_log "部署文件上传成功[$host]..."
        fn_log "执行启动命令[$host]..."
        ssh "admin@$host" 'jm rst'
        fn_log "启动命令执行完成[$host]..."
    done
}

function checkStatus() {
    # 休眠 0.5s
    sleep 0.5
    PID=$(getPid "$1")
    if ! ps -p "$PID" >/dev/null 2>&1; then
        #有error信息也按异常处理
        err_message=$(cat "$ERROR_LOG")
        log_error "The $jar_name started failed, cause: [$err_message]"
        exit 1
    fi
    log_info "The $jar_name (PID: $PID) started"
}

function monitoring() {
    jar_name="$JAR_NAME"
    if [[ -z "$jar_name" ]]; then
        log_error 'The JAVA_NAME have not been configured, please use [jm cfg] command to configure the jar name'
        exit 1
    fi
    #获取进程PID
    PID=$(getPid "$jar_name")
    if ! ps -p $PID >/dev/null; then
        log_error "Process with PID $PID does not exist."
        exit 1
    fi

    # 获取进程的名称
    PROCESS_NAME=$(ps -p $PID -o comm=)
    log_info "Monitoring process: $PROCESS_NAME (PID: $PID)"

    # 设置监控间隔（秒）
    INTERVAL=5

    count=0
    # 初始化网络 IO 数据
    NET_DEV=$(ip route show default | awk '/default/ {print $5}')
    PREV_RX=$(cat /proc/$PID/net/dev | grep $NET_DEV | awk '{print $2}')
    PREV_TX=$(cat /proc/$PID/net/dev | grep $NET_DEV | awk '{print $10}')


    #磁盘IO
    DISK_PREV_READ=$(cat "/proc/$PID/io" | grep -w "read_bytes" | awk '{print $2}')
    DISK_PREV_WRITE=$(cat "/proc/$PID/io" | grep -w "write_bytes" | awk '{print $2}')
    #GC
    FULL_GC_COUNT=N/A
    YONG_GC_COUNT=N/A

    while true; do
        TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

        # 获取 CPU 和内存使用情况
        CPU=$(top -b -n1 -p $PID | grep $PID | awk '{print $9}')
        MEM=$(top -b -n1 -p $PID | grep $PID | awk '{print $6}' | sed 's/g//')

        # 获取网络 IO
        RX=$(cat /proc/$PID/net/dev | grep $NET_DEV | awk '{print $2}')
        TX=$(cat /proc/$PID/net/dev | grep $NET_DEV | awk '{print $10}')
        RX_RATE=$(((RX - PREV_RX) / INTERVAL / 1024 ))
        TX_RATE=$(((TX - PREV_TX) / INTERVAL / 1024 ))
        PREV_RX=$RX
        PREV_TX=$TX

        # 获取磁盘IO
        DISK_READ=$(cat "/proc/$PID/io" | grep -w "read_bytes" | awk '{print $2}')
        DISK_WRITE=$(cat "/proc/$PID/io" | grep -w "write_bytes" | awk '{print $2}')
        DISK_READ_RATE=$(((DISK_READ - DISK_PREV_READ) / INTERVAL / 1024 ))
        DISK_WRITE_RATE=$(((DISK_WRITE - DISK_PREV_WRITE) / INTERVAL / 1024 ))
        DISK_PREV_READ=$DISK_READ
        DISK_PREV_WRITE=$DISK_WRITE
         

        # 获取 Full GC 次数
        GC_OUTPUT=$(jstat -gc $PID 2>/dev/null)
        if [ $? -eq 0 ]; then
            YONG_GC_COUNT=$(echo "$GC_OUTPUT" | awk 'NR==2 {print $13}')
            FULL_GC_COUNT=$(echo "$GC_OUTPUT" | awk 'NR==2 {print $15}')
        fi

        # 打印结果
        remainder=$((count % 15))
        if (($remainder == 0)); then
            # 输出表头
            echo -e "Timestamp\t\tCPU(%)\tMemory(GB)\tNet In(KB/s)\tNet Out(KB/s)\tD Read(KB/s)\tD Write(KB/s)\tYGC Count\tFGC Count"
        fi

        echo -e "$TIMESTAMP\t$CPU\t$MEM\t\t$RX_RATE\t\t$TX_RATE\t\t$DISK_READ_RATE\t\t$DISK_WRITE_RATE\t\t$YONG_GC_COUNT\t\t$FULL_GC_COUNT"
        ((count++))
        # 等待指定的间隔
        sleep $INTERVAL
    done
}

ARGS=''
ARG_KEY=''
ARG_PREFIX='-'
function doGetArg() {
    local val=''
    while true; do
        case "$1" in
        "${ARG_PREFIX}${ARG_KEY}")
            val="$2"
            break
            ;;
        --)
            shift
            break
            ;;
        *)
            shift
            ;;
        esac
    done
    echo "${val}"
}
function getArg() {
    local val=''
    parse_args "$@"

    if [[ -z "${ARGS}" ]]; then
        echo ''
    fi

    if [[ -z "${ARG_KEY}" ]]; then
        echo ''
    fi

    parameters=$(getopt -u -q -o "${ARG_KEY}:" -l "${ARG_KEY}:" -- $ARGS)

    doGetArg $parameters

}

function parse_args() {
    parameters=$(getopt -o 'l,a:,k:' -n "$0" -- "$@")
    eval set -- "$parameters"
    while true; do
        case "$1" in
        -a | args)
            ARGS="$2"
            shift 2
            ;;
        -l | long)
            ARG_PREFIX="--"
            shift
            ;;

        -k | --arg-key)
            ARG_KEY="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            shift
            ;;
        esac
    done
}
function has_arg() {
    if [[ "$1" == *"$2"* ]]; then
        echo "true"
    else
        echo 'false'
    fi
}

function help() {
    echo -e "
\033[32mWelcome to jmonitor tools!\033[0m

usage: jm <sub_cmd>

sub_cmd:
    \033[33mini\033[0m Initionlized JMonitor Tools' configuration,
        the old configuration will be overwritten e.g. jm ini
    \033[33mcfg\033[0m Configure the JMonitor Tools e.g. jm cfg
    \033[33mrst\033[0m restart a app, e.g. jm rst
    \033[33mstp\033[0m stop a app, e.g. jm stop
    \033[33mlg\033[0m show the logs of the server, e.g. jm lg show info log; jm lg -e show error log
    \033[33mmon\033[0m monitor a app, e.g. jm mon
    \033[33mps\033[0m Find the process like using ps -ef|grep xx, e.g. jm ps
    \033[33mdp\033[0m deploy to host, e.g. jm dp
    \033[33mrrst\033[0m restart a app that in the remote host, e.g. jm rrst
    \033[33mrstp\033[0m stop a app that in the remote host, e.g. jm rstp
"
}

function log_info() {
    log_prefix="JMonitor[$(date "+%Y-%m-%d %H:%M:%S")]:"
    echo -e "\033[32m$log_prefix $*\033[0m"
}

function log_error() {
    log_prefix="JMonitor[$(date "+%Y-%m-%d %H:%M:%S")]:"
    echo -e "\033[31m$log_prefix $*\033[0m"
}

function fn_log() {
    if [ $? -eq 0 ]; then
        #有error信息也按异常处理
        err_message=$(cat "$ERROR_LOG")
        if [[ -n "${err_message}" ]]; then
            log_error "$1 failed , cause: [$err_message]"
            exit 1
        fi
        log_info "$1 sucessfully"
    else
        err_message=$(cat "$ERROR_LOG")
        log_error "$1 failed , cause: [$err_message]"
        exit 1
    fi
    # 清空error log
    echo '' >"$ERROR_LOG"
}

function check_profile() {
    if [[ ! -e $PROFILE_FILE ]]; then
        log_info "Jmonitor Tools has not been configured yet, please use [jm -h] to check how to configure it."
        exit 1
    fi
}

function do_init_profile() {
    cat <<EOF >$PROFILE_FILE
################################################# 应用启动配置 ###################################################    
APP_PATH='/app'  
JAR_NAME='ifrs17_cic_measure_engine-1.0-SNAPSHOT.jar'

# 日志配置（用以读取日志）
APP_LOGS_PATH=\${APP_PATH}/logs
APP_LOGS_INFO_FILE=\${APP_LOGS_PATH}/sys_info.log
APP_LOGS_ERROR_FILE=\${APP_LOGS_PATH}/sys_error.log

JVM_OPTIONS='
-Xms2g -Xmx2g 
-Dspring.profiles.active=local
-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=35099
-Dcom.sun.management.jmxremote.rmi.port=7700
-Djava.rmi.server.hostname=$(hostname -I | awk '{print $1}')
-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
'

################################################# 应用部署配置 ###################################################
# 要上传部署的jar包路径
APP_SOURCE_PATH=''
# 要部署的目标服务器路径，使用空格分隔多个host
DEPLOY_HOSTS='xx.xx.xx.xx xx.xx.xx.xx'
EOF
    log_info "The configuration file initialized, please use [jm cfg] command to configure the JMonitor Tools"
}

function init_profile() {
    if [[ ! -e $PROFILE_FILE ]]; then
        fn_log "Initialize the configuration file..."
        do_init_profile
    fi
}

function main() {
    #获取子命令和参数
    sub_cmd=$1
    orther_args="${*:2}"
    case "${sub_cmd}" in
    rst)
        # 前置检查
        check_profile
        restart "$orther_args"
        ;;
    stp)
        # 前置检查
        check_profile
        stop "$orther_args"
        ;;
    lg)
        # 前置检查
        check_profile
        show_log "$orther_args"
        ;;
    mon)
        # 前置检查
        check_profile
        monitoring "$orther_args"
        ;;
    cfg)
        init_profile
        vim $PROFILE_FILE
        ;;
    ini)
        do_init_profile
        vim $PROFILE_FILE
        ;;
    ps)
        check_profile
        jar_name=$JAR_NAME
        pgrep -a -f  $jar_name
        ;;
    dp)
        check_profile
        deploy
        ;;
    rrst)
        check_profile
        remote_restart
        ;;
    rstp)
        check_profile
        remote_stop
        ;;
    -h)
        help
        ;;
    *)
        help
        ;;
    esac
}

main "$@"
